name: CI Deploy Application

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm install
    - run: npm run build --if-present  

    - name: Runnnig Tests
      run: |
        touch .env
        echo ${{ secrets.API_SECRET_JWT }}
        echo API_SECRET_JWT =${{ secrets.API_SECRET_JWT }} >> .env  
        npm test
      env:
        API_SECRET_JWT: ${{ secrets.API_SECRET_JWT }}

    - name: Removing .env File
      run: rm .env

