name: CI Deploy Application

on:
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    services:
      mysql:
        image: mysql:5.7
        env:
          DB_USERNAME: root
          DB_PASSWORD: password
          DB_DATABASE: test
          DB_PORT: 3306
          DB_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Setting Checkout
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Running CI
      run: |
        npm ci

    - name: Running Install
      run: |
        npm install

    - name: Running Build
      run: |
        npm run build --if-present  

    - name: Runnnig Tests
      run: |
        npm test
      env:
        API_SECRET_JWT: ${{ secrets.API_SECRET_JWT }}